name: Deploy Terraform to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger support

jobs:
  terraform:
    runs-on: self-hosted

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # Adjust based on your version
    - name: azure login
      run: az login

    # Configure Azure credentials
    - name: Azure login
      uses: azure/login@v2
      with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
    # Terraform Init
   # - name: Terraform Init
    #  run: terraform init

    # Terraform Plan
   # - name: Terraform Plan
    #  env:
     #   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        
     # run: terraform plan -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
      #                    -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
                          

    # Terraform Apply
  #  - name: Terraform Apply
   #   env:
   #     ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
   #     ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
   #     ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
   #     ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
   #   run: terraform apply -auto-approve -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
   #                        -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
   #                        -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
   #                        -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
