name: Deploy Terraform to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger support

jobs:
  terraform:
    runs-on: self-hosted

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install unzip
      run: sudo apt-get update && sudo apt-get install -y unzip

    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # Adjust based on your version
    
    # Configure Azure credentials
    - name: Azure login
      uses: azure/login@v2
      with:
          auth-type: SERVICE_PRINCIPAL
          tenant_id: ${{ secrets.tenant_id }}
          subscription_id: ${{ secrets.subscription_id }}
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false
           
      env:
          TERRAFORM_CLI_PATH: /home/azureuser/actions-runner/_work/_temp/1dde1f88-2411-4396-881b-9667713c5b8c
      
          
    # Terraform Init
   # - name: Terraform Init
    #  run: terraform init

    # Terraform Plan
   # - name: Terraform Plan
    #  env:
     #   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        
     # run: terraform plan -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
      #                    -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
                          

    # Terraform Apply
  #  - name: Terraform Apply
   #   env:
   #     ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
   #     ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
   #     ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
   #     ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
   #   run: terraform apply -auto-approve -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
   #                        -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
   #                        -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
   #                        -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
